### ISSUE TITLE
Find and integrate a 3D library

### ISSUE THREAD

**Issue by peterGraf** [ARVOS-APP/ArViewer_Android#1]

**Comment by sre42** [comment]
Hi Peter, how about JMonkeyEngine 3 as a 3D Library?

**Comment by peterGraf** [comment]
Hello Omar,

thanks for bringing the JMonkeyEngine 3 engine to my attention.

The one problem I see with it, is that it is Java and I currently do not see a way to port it to iOS.

I would also like to quit this issue here and reopen another one at the newly created MAIN project for ARVOS https://github.com/peterGraf/ARVOS/issues
